export const _LOAD_ALL_PRODUCTS = "LOAD_ALL_PRODUCTS";
export const _LOAD_ALL_SERIES = "LOAD_ALL_SERIES";
export const _LOAD_ALL_CHARACTERS = "LOAD_ALL_CHARACTERS";
export const _LOAD_ALL_COMICS = "LOAD_ALL_COMICS";
