export const _REMOVE_CHARACTER = "REMOVE_CHARACTER";
export const _REMOVE_SERIES = "REMOVE_SERIES";
export const _SAVE_CHARACTER = "SAVE_CHARACTER";
export const _SAVE_SERIES = "SAVE_SERIES";
export const _INITIALISE_SAVED_LIST_CHARACTER =
  "INITIALISE_SAVED_LIST_CHARACTER";
export const _INITIALISE_SAVED_LIST_SERIES = "INITIALISE_SAVED_LIST_SERIES";
